### ISSUE TITLE
Snow bug

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#10]
snow sphere is required to give 1 profit but does not.

Default: https://prnt.sc/mli4e7
Drop2Inventory: http://prntscr.com/mli5zj

**Comment by mfnalex** [comment]
Fixed: #5e3fd74b271d33d172b95ceb92abe25eb4d579a1

will be included in the next update

**Comment by successed** [comment]
thanks.
