### ISSUE TITLE
Ultimate Timber Bugs..

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#12]
This prevents using the add-on,https://www.spigotmc.org/resources/ultimatetimber-the-realistic-tree-chopper-formerly-treeassist.16941/

**Comment by successed** [comment]
The tree breaking feature provided by this plugin is unfortunately not working.

**Comment by mfnalex** [comment]
The UltimateTimber plugin seems to use a broken or weird detection system. The BlockBreakEvent is indeed cancelled. UltimateTimber must change its listener priority.
You could also just use my own tree gravity plugin **_LumberJack,_** which works perfectly with Drop2Inv: https://www.spigotmc.org/resources/1-13-lumberjack.60306/

**Comment by successed** [comment]
oke i disable Ultimate Timber and use lumberjack wait, lumberjack does it support the profession add-on? i have jobs reporn.
