### ISSUE TITLE
timings big problem 1.14.2

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#18]
http://prntscr.com/nvjccy

**Comment by mfnalex** [comment]
Thank your for the report, that is strange indeed. Drop2Inventory does nearly NO time intensive calculations. Do you always get results like that? Maybe there was an update/something else running in the background taking up resources.

Please tell me if the problem persits, however it would be very surprising.

**Comment by mfnalex** [comment]
Please reopen if this is still an issue
