### ISSUE TITLE
Tag problem on 1.14.x

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#19]
This plugin work on 1.14.x and item tag is verry bad.

NBT tag disable please.

**Comment by mfnalex** [comment]
I don't understand the problem. Can you please explain the problem further?

**Comment by successed** [comment]
> I don't understand the problem. Can you please explain the problem further?

normal block : http://prntscr.com/o5dz8c
problem block : http://prntscr.com/o5dzc1

tagged items do not stack.
When we break the block comes the tagged block.

**Comment by Bilibox** [comment]
Can confirm. 

When breaking a block with Drop2Inv enabled there is a chance of the block being picked up to have a NBT tag added to the item, making it unable to stack. With drop2inv disabled this is no longer the case.

Steps to reproduce:
1. Enable drop 2 inv
2. Break a flower over and over until you get a NBT flag
3. Disable Drop 2 inv
4. Place flower down, break it, no NBT flag

**Comment by mfnalex** [comment]
Thanks for the report. I will investigate this when I have time

**Comment by mfnalex** [comment]
this has been fixed in some recent version
