### ISSUE TITLE
Durability doesn't work

### ISSUE THREAD

**Issue by Legowyn** [JEFF-Media-GbR/Spigot-Drop2Inventory#2]
Hi Jeff,

I've an issue : All tools doesn't lost Durability, except when i attack a monster. 

Last version of spigot
Just one plugin : Drop2Inventory

Thanks for your help !

**Comment by mfnalex** [comment]
LOL good point, I wonder how noone noticed this before. I will change that soon. Thanks.

**Comment by mfnalex** [comment]
There is no way to check for the max durability of an item I think. So, I cannot just add damage to the tool, because the value might become bigger than the max durabilty, meaning the item will have negative damage.

**Comment by mfnalex** [comment]
I could hardcode the durability for diamond, gold, iron, stone and wooden tools, however that would lead to problems with enchantments.

**Comment by mfnalex** [comment]
I have fixed this by using Material.getType.getMaxDurability or something. I don't know why I didn't thought of that earlier...
