### ISSUE TITLE
1.14.3 Big bug!

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#21]
1.14.3 i break ores stone pickaxe then given to me diamond :D

**Comment by mfnalex** [comment]
You mean you always get diamonds when breaking any ore with a stone pickaxe?

**Comment by successed** [comment]
> You mean you always get diamonds when breaking any ore with a stone pickaxe?

When I don't have any items, when I break the ore, the diamond comes.

**Comment by mfnalex** [comment]
everything works fine for me
