### ISSUE TITLE
Torches, poppies, etc above blocks disappear when breaking block below it

### ISSUE THREAD

**Issue by zapteryx** [JEFF-Media-GbR/Spigot-Drop2Inventory#27]
This issue occurs in the latest version (3.9.4), and it doesn't drop torches or anything above the block. It just destroys the item entirely.

**Comment by mfnalex** [comment]
I don't really know how to fix this.

There is no method to check what a BlockBreakEvent really drops. Also it would be tedious to check for each and every possibly attached item on a block. Maybe I will have an idea later

**Comment by zapteryx** [comment]
What perplexes me is why the block above it disappears instead of dropping,
which is the current behaviour of the cactus, sugar cane and kelp.

**Comment by mfnalex** [comment]
That happens because I set BlockBreakEvent#setDropItems(boolean) to false. There is no method to check the "real" drops of a BlockBreakEvent, so I don't know right now what I could do to prevent this except adding a check for each block where this happens.

**Comment by zapteryx** [comment]
Maybe instead of setting setDropItems to false from the BlockBreakEvent,
try looking into BlockDropItemEvent?

**Comment by mfnalex** [comment]
Thanks, that's awesome. I already saw that when I started the plugin in 1.13, but all methods were marked as deprecated, strange.

**Comment by zapteryx** [comment]
That is indeed strange. I'm glad I could help. I assume this should fix #28 as well?

**Comment by mfnalex** [comment]
I hope so :)

**Comment by mfnalex** [comment]
at least cacti still only drop the "base" block

**Comment by mfnalex** [comment]
this will break compatability with versions before 1.13 but I don't think anyone cares about that

**Comment by mfnalex** [comment]
closed in 706f831c921611e774a66530d55084d5ce8c11ef

**Comment by zapteryx** [comment]
I've verified that this issue was fixed by the update, but #28 is still not fixed.

**Comment by zapteryx** [comment]
> Thanks, that's awesome. I already saw that when I started the plugin in 1.13, but all methods were marked as deprecated, strange.

Just a little note, I found out that the reason why they were marked deprecated was because they were draft API.
