### ISSUE TITLE
Kelp (and cactus, etc) only invdrops base block

### ISSUE THREAD

**Issue by zapteryx** [JEFF-Media-GbR/Spigot-Drop2Inventory#28]
The rest of the kelp (or cactus, sugar cane, etc) are dropped on the ground.

**Comment by zapteryx** [comment]
Most likely fixed in #27

**Comment by mfnalex** [comment]
What blocks exactly are affected beside kelp, Sugar cane and cactus?

**Comment by zapteryx** [comment]
Yep, seems like anything that grows above the base block like kelp, sugar cane and cactus are affected. I'll look for any more of these blocks and let you know here, if any.

**Comment by zapteryx** [comment]
A few more include bamboo and chorus plants.

**Comment by zapteryx** [comment]
The 1.16 update also introduces twisting vines, but I'm not sure if those are affected as well because they don't always drop all the vines.

**Comment by mfnalex** [comment]
I will have to manually count the plant parts. Chorus will be a bit complicated^^

**Comment by zapteryx** [comment]
Chorus will indeed be complicated. I can think of a few ways, one being to run a loop and repeatedly check the block above the broken one to see if it's a continued block (for example sugar cane), which should be similar to yours since it's essentially counting it. It doesn't cancel the drops for the ones above it though, so you'll have to find a way to cancel those as well. I did a lot of research on Spigot forums and such, but nobody really has a "proper" solution. Some also say that you can probably just take whatever that drops around the player that match the block broken and put it into their inventory and despawn it from the ground, although I'm not sure how you want to approach this problem. I'll keep looking and I'll try to help as much as I can.

**Comment by zapteryx** [comment]
If you were to go with the loop method, you can potentially solve the issue with chorus by checking the adjacent blocks on each loop to see if there's a chorus fruit / flower there, and keep checking for each chorus fruit you encounter (basically continue looping for each one), and stop when you reach the chorus flower. Just an idea though.

**Comment by zapteryx** [comment]
> If you were to go with the loop method, you can potentially solve the issue with chorus by checking the adjacent blocks on each loop to see if there's a chorus fruit / flower there, and keep checking for each chorus fruit you encounter (basically continue looping for each one), and stop when you reach the chorus flower. Just an idea though.

An issue with this is that I believe they _can_ grow next to each other, so honestly I'm not really sure how you could check that. I'll continue looking for ways to solve the issue as well.

**Comment by mfnalex** [comment]
the current commit has one problem, which I cannot explain to myself: when breaking kelp, the highest (and only the highest) plant part is dropped naturally.

**Comment by mfnalex** [comment]
I found the problem, it's because the uppermost part is called KELP instead of KELP_PLANT

**Comment by zapteryx** [comment]
I see, that would explain it. Anything for the rest of the blocks?

**Comment by mfnalex** [comment]
Everything seems to work fine so far, I am just finishing the Chorus stuff.

I had a look at the wiki and I am wondering if the following is true?
1. Chorus trees consist only of Chorus_Plant and Chorus_Flower
2. Chorus_Plant always has 50% drop chance
3. Chorus_Flower always has 100% drop chance

**Comment by zapteryx** [comment]
It seems like it is. I trust the official MC wiki the most, and I assume the wiki you're referring to should be the same one, so yes. Chorus Flower should indeed have a 100% drop chance, and Chorus Plant has a 50% drop chance. The Chorus trees do seem to only consist of both of these items as well.

**Comment by mfnalex** [comment]
It seems to be a bit different:

1. Chorus flower has 100% drop rate, but only if broken directly. When breaking the chorus tree from below, not single chorus flower drops
2. Chorus plant does not drop itself, but it will drop a chorus fruit (with 50% probability)

I am still having some issues with the drops of chorus trees :/

**Comment by mfnalex** [comment]
OMG I am so stupid. I called the wrong method the whole time, so its no surprise it didnt work correctly.

**Comment by zapteryx** [comment]
Ah. I assume you've found a good way to fix this then?

**Comment by mfnalex** [comment]
update is released :)

**Comment by zapteryx** [comment]
Thanks! I'll try it out.

**Comment by zapteryx** [comment]
Works perfectly! Thanks.
