### ISSUE TITLE
Heads from external plugin show base64 string as name when dropped

### ISSUE THREAD

**Issue by zapteryx** [JEFF-Media-GbR/Spigot-Drop2Inventory#29]
I'm not sure if this actually has to do with an external plugin, but when breaking a head, it sets the name as a base64 string instead of the actual name itself: https://m.zptx.icu/8d46sp.png

This fixes itself when I drop the item and pick it back up.

**Comment by mfnalex** [comment]
what head plugin are you using?

I tried it myself with HeadDatabase, and although the original skull name is lost, the name is simply shown as "Player head".

**Comment by zapteryx** [comment]
I actually forgot to mention that, the plugin is MoreMobHeads. Player heads
dropped by the plugin are fine but mob heads aren't.

**Comment by mfnalex** [comment]
I cannot fix this without saving the skull meta as file or something everytime a player places a head. You probably do NOT want this. I suggest you just add player_head to your blacklisted items.

If it's important to you, I could have a look at MMH's source code to see if I can fix it there.

**Comment by zapteryx** [comment]
It isn't really important to me, but if you could help fix it on MMH's side, that'd be great. This issue is fixed by dropping and picking up the item anyway, but still seems like a fairly annoying bug that I wouldn't want my players to see.
