### ISSUE TITLE
Mcmmo Support

### ISSUE THREAD

**Issue by Sakanas** [JEFF-Media-GbR/Spigot-Drop2Inventory#3]
I love this plugin but I have to stop using it because when I use it the mcmmo does not have the woodcutter xp for example, I do not know if you can understand, I'm Brazilian and I do not know English

**Comment by mfnalex** [comment]
I don't think mcMMO provides an API for that, sorry.

**Comment by Sakanas** [comment]
okay

Em qua, 26 de dez de 2018 às 12:49, JEFF <notifications@github.com>
escreveu:
