### ISSUE TITLE
When XP goes straight to inventory it ignores the mending enchant

### ISSUE THREAD

**Issue by TheMinesweep3r** [JEFF-Media-GbR/Spigot-Drop2Inventory#30]

**Comment by mfnalex** [comment]
How exactly does mending work - it only triggers a repeair when
1. the player gets XP while having a mending item in their hand, off hand or armor slot
2. an item with mending anywhere in the inventory needs repair

is that true?

**Comment by zapteryx** [comment]
Only triggers for items that need repair and are in hand, off hand or armor slot.

**Comment by mfnalex** [comment]
That is the default vanilla behaviour according the wiki, isnt it?

**Comment by mfnalex** [comment]
Sorry, I forgot to mention that that is the way Drop2Inv handles it currently. On spigot versions below 1.16 it tries to repair any equipped mending item, and on 1.16+ it picks a random damaged equipped mending item, just like in the corresponding vanilla version.
There should be no differences between using Drop2Inv or not. Please close this issue if that‘s correct :)
