### ISSUE TITLE
Paintings can't be broken while drop2inv is enabled

### ISSUE THREAD

**Issue by zapteryx** [JEFF-Media-GbR/Spigot-Drop2Inventory#33]
I recently tried to break a painting with drop2inv enabled but couldn't. Upon disabling it, I was able to break it as per normal.

**Comment by mfnalex** [comment]
oh, that's bad, I will fix that. Does the painting not go into the inventory or is it not possible to break them at all?

**Comment by zapteryx** [comment]
Can't break them at all.

**Comment by mfnalex** [comment]
ok, I'm going to fix that, thanks

**Comment by mfnalex** [comment]
fixed in 4.3.1
