### ISSUE TITLE
ocean 1.13.2 bug.

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#4]
When activated, you cannot get corals in the ocean with the items where the silky spell is printed.

**Comment by mfnalex** [comment]
Thanks I will put this on my todo list

**Comment by mfnalex** [comment]
coral drops should work when using a silk touch enchanted pickaxe. does the vanilla silk touch also work when using shovels or something on corals?

**Comment by mfnalex** [comment]
the new version should work will all tools that have silk touch, please tell me if this fixes the problem

**Comment by successed** [comment]
yes, this a fixed.
