### ISSUE TITLE
1.17.1 Glow_Item_Frame drops

### ISSUE THREAD

**Issue by x1p** [JEFF-Media-GbR/Spigot-Drop2Inventory#41]
When Glowing Item Frames are broken, they are picked up by Drop2Inventory.
However, the glowing effect is gone. The item frame has become a normal, non-glowing item frame.

Without Drop2Inventory the glowing item frame drops to the ground, can be picked up and remains a glowing item frame.

I tried to exclude this entity but it doesn't seem to be recognized
```yaml
disabled-mobs:
- GLOW_ITEM_FRAME
```
It appears to be handled as a block but I can't disable it.
```yaml
disabled-blocks:
- GLOW_ITEM_FRAME
```

**Comment by mfnalex** [comment]
Thanks for reporting - I assume you are using the free version, right? Because it's working fine in the paid version, I haven't tested the free version yet

**Comment by x1p** [comment]
Eh paid version? I missed that update. I'll dm you shortly.
