### ISSUE TITLE
Potato,Wheat, Carrot bug!

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#8]
When we break agricultural products like freshly grown potato carrots, only 1 piece comes in. Seed Normally 2 3 pieces are given.

**Comment by successed** [comment]
http://prntscr.com/mlhu9b
2 different names of seeds.
1 : http://prntscr.com/mlhul4
2 : http://prntscr.com/mlhuoz

**Comment by successed** [comment]
this is especially experienced in potatoes.

**Comment by mfnalex** [comment]
both has been fixed
